# Generated by Django 5.1.6 on 2025-03-24 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetariobase', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetaingrediente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetaingrediente',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='porcentaje_panadero',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre', 'tipo'), name='unique_marca_nombre_tipo'),
        ),
    ]
